### ISSUE TITLE
Denied acces to repo

### ISSUE THREAD

**Issue by EQLucky** [KaOS-Community-Packages/discord#1]
Hi there.

Today I wanted to update some packages (mainly discord, as requested), but I couldn't.
I can't push to the repo:
```
 eqlucky  ~  github  slack  git push                                                                  master 
Username for 'https://github.com': eqlucky@gmail.com
Password for 'https://eqlucky@gmail.com@github.com': 
remote: Permission to KaOS-Community-Packages/slack.git denied to EQLucky.
fatal: unable to access 'https://github.com/KaOS-Community-Packages/slack.git/': The requested URL returned error: 403
```

Does anyone know which could it be? I followed the same steps as before...

**Comment by bvaudour** [comment]
Hi,

The repo was created by an admin, that blocks by default the write-permission for other members. Can you test again for slack? Concerning Discord, you shouldn’t have issue (you created the repo, so you are marked as admin of the repo).

**Comment by demmm** [comment]
>that blocks by default the write-permission for other members

that would be awful if that is the case now, KCP was setup so all members have access to all packages

**Comment by EQLucky** [comment]
> Hi,
> 
> The repo was created by an admin, that blocks by default the write-permission for other members. Can you test again for slack? Concerning Discord, you shouldn’t have issue (you created the repo, so you are marked as admin of the repo).

I double checked my credentials (as I use my ghp key instead of my password, as github requested) and I've checked my ~/.gitconfig file, where there's only my email account as [user].
Do you know any workarounds?

**Comment by demmm** [comment]
Which repo tried last? Discord?
Do you have web access still to members only sections? Example https://github.com/orgs/KaOS-Community-Packages/dashboard

**Comment by EQLucky** [comment]
> Which repo tried last? Discord? Do you have web access still to members only sections? Example https://github.com/orgs/KaOS-Community-Packages/dashboard

I've just tried Discord:
```
 eqlucky  ~  github  discord  git push                                                                  main 
Username for 'https://github.com': eqlucky@gmail.com
Password for 'https://eqlucky@gmail.com@github.com': 
remote: Permission to KaOS-Community-Packages/discord.git denied to EQLucky.
fatal: unable to access 'https://github.com/KaOS-Community-Packages/discord.git/': The requested URL returned error: 403
```

And yeah, I still have access to those sections via web.

**Comment by demmm** [comment]
And you still use the same password for web acces as for git access?  That has not been possible on my end for over a year.....
You need to use a personal access token.

**Comment by MartinVonReichenberg** [comment]
**Everything should be working by now . . .**
